name: Main Workflow
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.x
    - name: Add nuget feed
      run: dotnet nuget add source --username gwairslip --password ${{ secrets.GW_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/airslip-ltd/index.json"
    - name: Install dependencies
      run: dotnet restore ./src/Airslip.Identity.sln
    - name: Build
      run: dotnet build ./src/Airslip.Identity.sln --no-restore
    - name: Test
      run: dotnet test ./src/Airslip.Identity.sln --no-build --verbosity normal
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: src
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}