name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: |
        nuget sources add -name "private-packages" -source https://nuget.pkg.github.com/airslip-ltd/index.json -username ${env:PACKAGES_TOKEN} -password ${env:PACKAGES_TOKEN} -StorePasswordInClearText
        dotnet restore 
      working-directory: src
    - name: Build
      run: dotnet build --no-restore
      working-directory: src
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: src
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.6
      with:
       projectBaseDir: src
