name: Deploy dotnet Web Application

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-web-app-dev:
    runs-on: ubuntu-latest
    environment: Development
    env:
      DOTNET_CORE_VERSION: 6.0.x
      PUBLISH_PATH: ./src/Airslip.Identity.Api
      RESOURCE_GROUP_NAME: airslip-dev-resources
      APPSERVICE_NAME: airslip-dev-identity-api
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

    - uses: cschleiden/replace-tokens@v1
      with:
        files: '["${{ env.PUBLISH_PATH }}/*.json"]'
      env:
        LOGZ_IO_AUTH_TOKEN: ${{ secrets.LOGZ_IO_AUTH_TOKEN }}
        LOGZ_IO_ENVIRONMENT: Development
        LOGZ_IO_SERVICE_NAME: ${{ env.APPSERVICE_NAME }}
        LOGZ_IO_HOSTING_NAME: Azure

    - name: Add nuget feed
      run: dotnet nuget add source --username ${{ secrets.PACKAGE_USER }} --password ${{ secrets.PACKAGE_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/airslip-ltd/index.json"
    - name: Install dependencies
      run: dotnet publish ${{ env.PUBLISH_PATH }} -c Release -o MyWebApp

    - name: Get AppService publish profile
      id: publishprofile
      uses: aliencube/publish-profile-actions@v1
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_PROD_DEPLOY }}
      with:
        resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
        appName: ${{ env.APPSERVICE_NAME }}

    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.APPSERVICE_NAME }}
        package: ./MyWebApp
        publish-profile: ${{ steps.publishprofile.outputs.profile }}
